import argparse

"""
Here are the param for the training

"""

def get_args():
    parser = argparse.ArgumentParser()
    # the environment setting
    parser.add_argument('--env-name', type=str, default='AntMaze-v1', help='the environment name')
    parser.add_argument('--test', type=str, default='AntMazeTest-v1')
    parser.add_argument('--n-epochs', type=int, default=100000, help='the number of epochs to train the agent')
    parser.add_argument('--n-batches', type=int, default=300, help='the times to update the network')
    parser.add_argument('--save-interval', type=int, default=5, help='the interval that save the trajectory')
    parser.add_argument('--seed', type=int, default=123, help='random seed')
    parser.add_argument('--num-workers', type=int, default=1, help='the number of cpus to collect samples')
    parser.add_argument('--replay-strategy', type=str, default='future', help='the HER strategy')
    parser.add_argument('--save-dir', type=str, default='saved_models/', help='the path to save the models')
    parser.add_argument('--noise-eps', type=float, default=0.2, help='noise eps')
    parser.add_argument('--buffer-size', type=int, default=int(1e6), help='the size of the buffer')
    parser.add_argument('--replay-k', type=int, default=5, help='ratio to be replace')
    parser.add_argument('--batch-size', type=int, default=128, help='the sample batch size')
    parser.add_argument('--gamma', type=float, default=0.98, help='the discount factor')
    parser.add_argument('--action-l2', type=float, default=0.5, help='l2 reg')
    parser.add_argument('--lr-actor', type=float, default=0.0001, help='the learning rate of the actor')
    parser.add_argument('--lr-critic', type=float, default=0.0001, help='the learning rate of the critic')
    parser.add_argument('--polyak', type=float, default=0.99, help='the average coefficient')
    parser.add_argument('--n-test-rollouts', type=int, default=10, help='the number of tests')
    parser.add_argument('--demo-length', type=int, default=20, help='the demo length')
    parser.add_argument('--cuda', action='store_true', help='if use gpu do the acceleration')
    #parser.add_argument('--num-rollouts-per-mpi', type=int, default=2, help='the rollouts per mpi')
    parser.add_argument('--network', type=str, default='critic', help='the network type')
    parser.add_argument('--metric', type=str, default='MLP', help='the corresponding metric')
    parser.add_argument('--device', type=str, default='cuda:0', help='cuda device')
    parser.add_argument('--search', type=bool, default=False)
    parser.add_argument('--plan-rate', type=float, default=0)
    parser.add_argument('--lr_decay_actor', type=int, default=100000)
    parser.add_argument('--lr_decay_critic', type=int, default=100000)
    parser.add_argument('--layer', type=int, default=7)
    parser.add_argument('--period', type=int, default=3)
    parser.add_argument('--distance', type=float, default=0.3)
    parser.add_argument('--resume', type=bool, default=True)
    parser.add_argument('--resume_epoch', type=int, default=1300)
    parser.add_argument('--path', type=str, default='saved_models/AntMaze-v1_May21_15-35-16')
    #args for the planner
    parser.add_argument('--fps', type=int, default=1)
    parser.add_argument('--landmark', type=int, default=700)
    parser.add_argument('--initial-sample', type=int, default=2000)
    parser.add_argument('--clip-v', type=float, default=-35.)
    args = parser.parse_args()
    return args

def get_args_pointmaze_v1():
    parser = argparse.ArgumentParser()
    # the environment setting
    parser.add_argument('--env-name', type=str, default='PointMaze-v1', help='the environment name')
    parser.add_argument('--test', type=str, default='PointMazeTest-v1')
    parser.add_argument('--n-epochs', type=int, default=7000, help='the number of epochs to train the agent')
    parser.add_argument('--n-batches', type=int, default=150, help='the times to update the network')
    parser.add_argument('--save-interval', type=int, default=5, help='the interval that save the trajectory')
    parser.add_argument('--seed', type=int, default=123, help='random seed')
    parser.add_argument('--num-workers', type=int, default=1, help='the number of cpus to collect samples')
    parser.add_argument('--replay-strategy', type=str, default='future', help='the HER strategy')
    parser.add_argument('--save-dir', type=str, default='saved_models/', help='the path to save the models')
    parser.add_argument('--noise-eps', type=float, default=0.2, help='noise eps')
    parser.add_argument('--random-eps', type=float, default=0.3, help='random eps')
    parser.add_argument('--buffer-size', type=int, default=int(1e6), help='the size of the buffer')
    parser.add_argument('--replay-k', type=int, default=5, help='ratio to be replace')
    parser.add_argument('--batch-size', type=int, default=128, help='the sample batch size')
    parser.add_argument('--gamma', type=float, default=0.98, help='the discount factor')
    parser.add_argument('--action-l2', type=float, default=1, help='l2 reg')
    parser.add_argument('--lr-actor', type=float, default=0.0002, help='the learning rate of the actor')
    parser.add_argument('--lr-critic', type=float, default=0.0001, help='the learning rate of the critic')
    parser.add_argument('--polyak', type=float, default=0.98, help='the average coefficient')
    parser.add_argument('--n-test-rollouts', type=int, default=10, help='the number of tests')
    parser.add_argument('--demo-length', type=int, default=20, help='the demo length')
    parser.add_argument('--cuda', action='store_true', help='if use gpu do the acceleration')
    #parser.add_argument('--num-rollouts-per-mpi', type=int, default=2, help='the rollouts per mpi')
    parser.add_argument('--network', type=str, default='critic', help='the network type')
    parser.add_argument('--metric', type=str, default='MLP', help='the corresponding metric')
    parser.add_argument('--device', type=str, default='cuda:0', help='cuda device')
    parser.add_argument('--search', type=bool, default=False)
    parser.add_argument('--plan-rate', type=float, default=0)
    parser.add_argument('--lr_decay_actor', type=int, default=100000)
    parser.add_argument('--lr_decay_critic', type=int, default=100000)
    parser.add_argument('--layer', type=int, default=7)
    parser.add_argument('--period', type=int, default=10)
    parser.add_argument('--distance', type=float, default=0.1)
    parser.add_argument('--resume', type=bool, default=True)
    parser.add_argument('--resume_epoch', type=int, default=6000)
    parser.add_argument('--path', type=str, default='saved_models/PointMaze-v1_May18_22-34-29')
    #args for the planner
    parser.add_argument('--fps', type=int, default=1)
    parser.add_argument('--random-epoch', type=int, default=0)
    parser.add_argument('--landmark', type=int, default=200)
    parser.add_argument('--initial-sample', type=int, default=1000)
    parser.add_argument('--clip-v', type=float, default=-4)
    parser.add_argument('--heat', type=float, default=0.9)
    args = parser.parse_args()
    return args